package uz.pdp.jwtsecure.utils;

public interface MessageConstants {

    String LOGIN_OR_PASSWORD_ERROR = "LOGIN OR PASSWORD ERROR";
    String USER_NOT_FOUND = "USER NOT FOUND";
    String PASSWORD_CAN_NOT_BE_EMPTY = "PASSWORD CAN NOT BE EMPTY";
    String PASSWORD_SHOULD_MATCH_REGEX = "PASSWORD SHOULD MATCH REGEX";
    String USER_PERMISSION_RESTRICTION = "USER PERMISSION RESTRICTION";
    String TOKEN_NOT_VALID = "TOKEN NOT VALID";
    String REFRESH_TOKEN_EXPIRED = "REFRESH TOKEN EXPIRED";
    String WRONG_ACCESS_TOKEN = "WRONG ACCESS TOKEN";
    String ACCESS_TOKEN_NOT_EXPIRED = "ACCESS TOKEN NOT EXPIRED";
    String DO_NOT_HAVE_PERMISSION_TO_USE_THIS_WAY = "DO NOT HAVE PERMISSION TO USE THIS_WAY";
    String PAGE_NOT_FOUND = "PAGE NOT FOUND";
    String METHOD_ERROR = "METHOD ERROR";
    String UNACCEPTABLE = "UNACCEPTABLE";

    String EMAIL_CAN_NOT_BE_EMPTY = "EMAIL_CAN_NOT_BE_EMPTY";
    String FIRST_NAME_CAN_NOT_BE_EMPTY = "FIRST NAME CAN NOT BE EMPTY";
    String LAST_NAME_CAN_NOT_BE_EMPTY = "LAST NAME CAN NOT BE EMPTY";
    String EMAIL_SHOULD_MATCH_REGEX = "EMAIL SHOULD MATCH REGEX";
    String PRE_PASSWORD_CAN_NOT_BE_EMPTY = "PRE_PASSWORD_CAN_NOT_BE_EMPTY";
    String PRE_PASSWORD_SHOULD_MATCH_REGEX = "PRE PASSWORD SHOULD MATCH REGEX";


    String USERNAME_CAN_NOT_BE_EMPTY = "USERNAME_CAN_NOT_BE_EMPTY";
    String UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS";
}
